---


- server_hosts:
   - "192.168.234.131  cacti01"
   - "192.168.234.132  cacti02"
   # 133はvip想定
   - "192.168.234.135  mssql01"
   - "192.168.234.136  mssql02"
   # 136はHAプロキシ想定


- prompt:
  # staging(33->Yellow)
  - \[\e[1;33m\][\u@\h \W]\\$ \[\e[m\]


#- ntp_upstream_servers:
#  - 10.39.64.3
#  - 10.39.72.3

#- dns:
#  - "10.39.175.12 10.39.119.76"

